
IF NOT EXISTS
(
    SELECT name 
    FROM SYSOBJECTS
    WHERE TYPE ='U' AND NAME ='T_Logs'
)
BEGIN

DROP TABLE dbo.t_Logs

CREATE TABLE [dbo].[t_Logs] (
    [Id]          INT             IDENTITY (1, 1) NOT NULL,
    [ZoneTableId]      INT  DEFAULT (0) NOT NULL,
    [LogLevel]    INT  DEFAULT (0) NOT NULL,
    [LogTime]     DATETIME        DEFAULT GETUTCDATE() NOT NULL,
    [LogOperator] NVARCHAR (256)  DEFAULT ('') NOT NULL,
    [IP]          NVARCHAR (256)  DEFAULT ('') NOT NULL,
    [Detail]      NVARCHAR (MAX)  DEFAULT ('') NOT NULL,
    [Remark]      NVARCHAR (1024) DEFAULT ('') NOT NULL
);


IF NOT EXISTS
(    SELECT *
	 FROM SYS.indexes
	 WHERE NAME = 'IX_T_Logs'
)

CREATE CLUSTERED INDEX IX_T_Logs_LogTime ON T_Logs
(
    [LogTime] DESC
)
with( PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
ON [PRIMARY];

CREATE NONCLUSTERED INDEX IX_T_Logs_ZONETABLEID ON T_Logs
(
    [ZONETABLEID] ASC
)
with( PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
ON [PRIMARY];

CREATE NONCLUSTERED INDEX IX_T_Logs_LOGLEVEL ON T_Logs
(
    [LOGLEVEL] ASC
)
with( PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
ON [PRIMARY];

END;
