IF NOT EXISTS
(
    SELECT name 
    FROM SYSOBJECTS
    WHERE TYPE ='U' AND NAME ='T_ZONE_INFO'
)
BEGIN

CREATE TABLE [dbo].[t_Zone_Info]
(
	[Id] INT IDENTITY(1,1) NOT NULL ,
	[ZoneId] nvarchar(512) NOT NULL DEFAULT '', 
	[ZoneName] nvarchar(256) NOT NULL DEFAULT '',
	[AuthEmail] nvarchar(256) NOT NULL DEFAULT '', 
	[AuthKey] nvarchar(256) NOT NULL DEFAULT '',
	[IfTestStage] int NOT NULL DEFAULT 1, 
	[IfEnable] int NOT NULL DEFAULT 1, 
	[IfAttacking] int NOT NULL DEFAULT 0, 
	Constraint [PK_t_Zone_Info] primary key clustered
	(
	  [Id] ASC
	)with( PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] ;

IF NOT EXISTS
(    SELECT *
	 FROM SYS.indexes
	 WHERE NAME = 'IX_T_ZONE_INFO_ZONEID'
)

CREATE NONCLUSTERED INDEX IX_T_ZONE_INFO_ZONEID ON T_ZONE_INFO
(
    [ZONEID] ASC
)
with( PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
ON [PRIMARY];
END;